import type { Folder, Note, SavedLink, Tag } from '@/db/types';
import type { BackupData, BackupMode, PortableSettings, StashBackup } from '@/lib/backup/format';

/**
 * Fixtures for backup documents.
 *
 * Built as plain objects rather than through any app code, because the tests
 * that use them aim the reader at documents our own writer did *not* produce. A
 * fixture generated by the exporter would only show that the two agree with each
 * other; these are the shapes a hand-written or third-party file can take.
 *
 * The row builders return the real entity types, so the ordinary cases are
 * type-checked like any other data. Cases that are deliberately malformed cast at
 * the call site, where the intent is visible in the test itself.
 */

export const BASE_TIME = 1_750_000_000_000;

export function folder(
  id: string,
  name: string,
  parentId: string | null = null,
  extra: Partial<Folder> = {},
): Folder {
  return {
    id,
    name,
    parentId,
    createdAt: BASE_TIME,
    updatedAt: BASE_TIME,
    sortOrder: 0,
    isFavorite: false,
    isLocked: false,
    ...extra,
  };
}

export function link(
  id: string,
  url: string,
  folderId: string | null = null,
  extra: Partial<SavedLink> = {},
): SavedLink {
  return {
    id,
    url,
    folderId,
    normalizedUrl: url,
    source: 'example.com',
    createdAt: BASE_TIME,
    updatedAt: BASE_TIME,
    isFavorite: false,
    isArchived: false,
    isLocked: false,
    ...extra,
  };
}

export function note(
  id: string,
  title: string,
  content: string,
  parentNoteId: string | null = null,
  extra: Partial<Note> = {},
): Note {
  return {
    id,
    title,
    content,
    parentNoteId,
    createdAt: BASE_TIME,
    updatedAt: BASE_TIME,
    sortOrder: 0,
    isFavorite: false,
    isArchived: false,
    isLocked: false,
    ...extra,
  };
}

export const DEFAULT_SETTINGS: PortableSettings = {
  themeMode: 'system',
  relockPolicy: 'immediate',
  lockApp: true,
  secureScreen: false,
  biometric: true,
  lastFolderId: null,
  recentFolderIds: [],
};

export function data(partial: Partial<BackupData> = {}): BackupData {
  return {
    folders: [],
    links: [],
    tags: [],
    linkTags: [],
    notes: [],
    noteLinks: [],
    settings: { ...DEFAULT_SETTINGS },
    ...partial,
  };
}

/**
 * A document, with the payload left loosely typed.
 *
 * The `data` field is `unknown` on purpose: half the point of these fixtures is
 * to hand the reader a payload that is *not* a valid `BackupData`, and typing it
 * as one would make those tests impossible to write.
 */
export interface WildDocument extends Omit<StashBackup, 'data'> {
  data?: unknown;
}

export function document(partial: Partial<WildDocument> = {}): WildDocument {
  return {
    format: 'stash-backup',
    version: 1,
    exportedAt: '2026-09-27T10:00:00.000Z',
    appVersion: '0.1.0',
    mode: 'sealed' as BackupMode,
    summary: {
      folders: 0,
      links: 0,
      tags: 0,
      notes: 0,
      linkTags: 0,
      noteLinks: 0,
      favorites: 0,
      archived: 0,
      sealedItems: 0,
    },
    ...partial,
  };
}

export function documentText(partial: Partial<WildDocument> = {}): string {
  return JSON.stringify(document(partial));
}

/** A small but complete vault: nested folders, links, tags, notes, favourites. */
export function sampleData(): BackupData {
  return data({
    folders: [
      folder('f-work', 'Work'),
      folder('f-work-reports', 'Reports', 'f-work'),
      folder('f-private', 'Private', null, { isLocked: true }),
    ],
    links: [
      link('l-1', 'https://example.com/a', 'f-work', { isFavorite: true }),
      link('l-2', 'https://example.com/b', 'f-work-reports'),
      link('l-3', 'https://secret.example.com/x', 'f-private'),
      link('l-4', 'https://example.com/archived', null, { isArchived: true }),
    ],
    tags: [
      { id: 't-read', name: 'to-read' } satisfies Tag,
      { id: 't-work', name: 'work' } satisfies Tag,
    ],
    linkTags: [
      { linkId: 'l-1', tagId: 't-read' },
      { linkId: 'l-2', tagId: 't-work' },
    ],
    notes: [
      note('n-root', 'Reading list', '# Reading list\n\nThings to read.', null, { isFavorite: true }),
      note('n-child', 'Chapter notes', 'Some thoughts.', 'n-root'),
      note('n-archived', 'Old', 'Old note.', null, { isArchived: true }),
    ],
    noteLinks: [
      { noteId: 'n-root', linkId: 'l-1', origin: 'attached', createdAt: BASE_TIME, sortOrder: 0 },
      { noteId: 'n-child', linkId: 'l-2', origin: 'created-from', createdAt: BASE_TIME, sortOrder: 1 },
    ],
  });
}
